<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use App\Models\BaseModel;
use App\Models\User;
use Carbon\Carbon;
use Auth;

class Blog extends BaseModel
{
    use HasFactory;
    protected static $table_name = 'blogs';
    protected $table = "blogs";
    public $class_name = 'App\Models\Blog';
    public $class_dynamic = true;
    protected $has_images = true;
    public $status_col = 'is_approved';

    protected $fillable = [
        'title','description','publisher','publish_at','author','is_active','is_delete','is_approved','slug'
    ];

    protected $rules = [];
    public function __construct(){
        parent::__construct();
        $this->setRules();
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $table = static::$table_name;

        static::addGlobalScope('active_blogs', function (Builder $builder) use($table){
            $user = Auth::user();
            if(isset($user) && $user->hasRole('admin')){
                $builder->where($table.'.is_delete', '=', 0);
            }
            else if(isset($user)){
                $builder->where($table.'.is_delete', '=', 0)->where('author',$user->id);
            }
            else{
                $builder->where($table.'.is_delete', '=', 0)->where($table.'.is_active','=',1)->where($table.'.is_approved',1);
            }

        });
    }


   

    public function getRecordDataTable($request){
        if($request->has('search') && $request->search !=''){
            $this->setFilters(['title','like','%'.$request->search.'%']);
        }

        $condition = [];
        $result = [];
        $this->setSelectedColumn(['id','title','slug','publisher','author','publish_at','created_at','is_active','is_approved']);

        $this->setRenderColumn([
            [
                'name' => 'id',
                'db_name' => 'id',
                'type' => 'integer',
                'html' => false,
            ],
            [
                'name' => 'title',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'slug',

            ],
            [
                'name' => 'slug',
                'type' => 'string',
                'html' => false,
            ],
            [
                'name' => 'publish_at',
                'type' => 'string',
                'html' => false,
            ],
            [
                'name' => 'publisher',
                'type' => 'string',
                'html' => false,
            ],
            [
                'name' => 'author',
                'type' => 'string',
                'html' => false,
            ],

            [
                'name' => 'created_at',
                'type' => 'string',
                'html' => false,
            ],
            [
                'name' => 'is_approved',
                'type' => 'boolean',
                'html' => false,

            ],
            [
                'name' => 'status',
                'type' => 'boolean',
                'html' => true,
                'condition_column' => 'is_approved',
                'class_dynamic' => false,
            ],


        ]);

        $result = $this->getAllDatatables([],
        $this->getSelectedColumns(),
        [],'',[]);

        return $result;
    }

    public function user(){
        return $this->belongsTo(User::class,'author');
    }

    public function getCreatedAtAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->format('M Y');
    }
}
