<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use App\Models\BaseModel;
use Auth;

class EventCalender extends BaseModel
{
    use HasFactory;
    protected static $table_name = 'event_calenders';
    protected $table = "event_calenders";
    public $class_name = 'App\Models\EventCalender';
    public $class_dynamic = true;
    protected $has_images = true;

    protected $fillable = [
        'title','description','is_active','is_delete','is_approved','event_date','price','venue','user_id',
        'slug','time','city','booking_link'
    ];

    protected $rules = [];
    public function __construct(){
        parent::__construct();
        $this->setRules();
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $table = static::$table_name;
        static::addGlobalScope('active_directories', function (Builder $builder) use($table) {
            $user = Auth::user();
            if(isset($user) && $user->hasRole('admin')){
                $builder->where($table.'.is_delete', '=', 0);
            }else if(isset($user)){
                $builder->where($table.'.is_delete', '=', 0)->where($table.'.is_active','=',1)->where('user_id',$user->id);
            }else{
                $builder->where($table.'.is_delete', '=', 0)->where($table.'.is_active','=',1)->where($table.'.is_approved',1);
            }
        });
    }


    public function getRecordDataTable($request){
        if($request->has('search') && $request->search !=''){
            $this->setFilters(['title','like','%'.$request->search.'%']);
        }

        $condition = [];
        $result = [];
        $this->setSelectedColumn(['id','title','created_at','is_active','is_approved','event_date','time','city','venue','price']);

        $this->setRenderColumn([
            [
                'name' => 'id',
                'db_name' => 'id',
                'type' => 'integer',
                'html' => false,
            ],
            [
                'name' => 'title',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'slug',

            ],
            [
                'name' => 'event_date',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'event_date',

            ],
            [
                'name' => 'time',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'time',

            ],
            [
                'name' => 'city',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'city',

            ],
            [
                'name' => 'venue',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'venue',

            ],
            [
                'name' => 'price',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'price',

            ],

            [
                'name' => 'created_at',
                'type' => 'string',
                'html' => false,
            ],
            [
                'name' => 'is_active',
                'type' => 'boolean',
                'html' => false,

            ],
            [
                'name' => 'is_approved',
                'type' => 'boolean',
                'html' => true,
                'condition_column' => 'is_approved',
                'class_dynamic' => false,
            ],


        ]);

        $result = $this->getAllDatatables([],
        $this->getSelectedColumns(),
        [],'',[]);

        return $result;
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
}
