<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use App\Models\BaseModel;
use Auth;

class PlatinumPartner extends BaseModel
{
    use HasFactory;
    protected static $table_name = 'platinum_partners';
    protected $table = "platinum_partners";
    public $class_name = 'App\Models\PlatinumPartner';
    public $class_dynamic = true;
    protected $has_images = true;
    public $status_col = 'is_approved';
    protected $fillable = [
        'title','description','is_active','is_delete','is_approved','web_url'
    ];

    protected $rules = [];
    public function __construct(){
        parent::__construct();
        $this->setRules();
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $table = static::$table_name;
        static::addGlobalScope('active_platinum_partners', function (Builder $builder) use($table){
            $user = Auth::user();
            if(isset($user) && $user->hasRole('admin')){
                $builder->where($table.'.is_delete', '=', 0);
            }else{
                $builder->where($table.'.is_delete', '=', 0)->where($table.'.is_active','=',1)->where($table.'.is_approved',1);
            }

        });
    }


    public function getRecordDataTable($request){
        if($request->has('search') && $request->search !=''){
            $this->setFilters(['title','like','%'.$request->search.'%']);
        }

        $condition = [];
        $result = [];
        $this->setSelectedColumn(['id','title','description','web_url','created_at','is_active','is_approved']);

        $this->setRenderColumn([
            [
                'name' => 'id',
                'db_name' => 'id',
                'type' => 'integer',
                'html' => false,
            ],
            [
                'name' => 'title',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'title',

            ],
            [
                'name' => 'description',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'description',

            ],
            [
                'name' => 'web_url',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'web_url',

            ],


            [
                'name' => 'created_at',
                'type' => 'string',
                'html' => false,
            ],
            [
                'name' => 'is_active',
                'type' => 'boolean',
                'html' => false,

            ],
            [
                'name' => 'is_approved',
                'type' => 'boolean',
                'html' => true,
                'condition_column' => 'is_approved',
                'class_dynamic' => false,
            ],


        ]);

        $result = $this->getAllDatatables([],
        $this->getSelectedColumns(),
        [],'',[]);

        return $result;
    }

    public function setTitleAttribute($title)
    {
        $slug = preg_replace("![^a-z0-9]+!i", "-", strtolower($title));

        if(isset($this->id)){
            $obj = self::where('slug',$slug)->where('id','!=',$this->id)->first();
            $this->attributes['slug'] = $slug.'-'.((int)$this->id);
           
          
        }
        $obj = self::where('slug',$slug)->first();
        if(isset($obj)){
            $this->attributes['slug'] = $slug.'-'.((int)$obj->id+1);
           
        }
        $this->attributes['slug'] = $slug;
        $this->attributes['title'] = $title;
    }
    // public function user(){
    //     return $this->belongsTo(User::class,'user_id');
    // }
}
