<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use App\Models\BaseModel;
use Auth;

class PlatinumPartner extends BaseModel
{
    use HasFactory;
    protected static $table_name = 'platinum_partners';
    protected $table = "platinum_partners";
    public $class_name = 'App\Models\PlatinumPartner';
    public $class_dynamic = true;
    protected $has_images = true;

    protected $fillable = [
        'title','description','is_active','is_delete','is_approved','web_url'
    ];

    protected $rules = [];
    public function __construct(){
        parent::__construct();
        $this->setRules();
    }

    // public static function boot()
    // {
    //     parent::boot(); // TODO: Change the autogenerated stub
    //     static::addGlobalScope('active_blogs', function (Builder $builder) {
    //         $user = Auth::user();
    //         if(isset($user) && $user->hasRole('admin')){
    //             $builder->where('blogs.is_delete', '=', 0);
    //         }else{
    //             $builder->where('blogs.is_delete', '=', 0)->where('blogs.is_active','=',1)->where('is_approved',1);
    //         }

    //     });
    // }


    public function getRecordDataTable($request){
        if($request->has('search') && $request->search !=''){
            $this->setFilters(['title','like','%'.$request->search.'%']);
        }

        $condition = [];
        $result = [];
        $this->setSelectedColumn(['id','title','created_at','is_active','is_approved']);

        $this->setRenderColumn([
            [
                'name' => 'id',
                'db_name' => 'id',
                'type' => 'integer',
                'html' => false,
            ],
            [
                'name' => 'title',
                'type' => 'string',
                'html' => false,
                'link' => 'property',
                'link_column' => 'title',

            ],


            [
                'name' => 'created_at',
                'type' => 'string',
                'html' => false,
            ],
            [
                'name' => 'is_active',
                'type' => 'boolean',
                'html' => false,

            ],
            [
                'name' => 'is_approved',
                'type' => 'boolean',
                'html' => true,
                'condition_column' => 'is_approved',
                'class_dynamic' => false,
            ],


        ]);

        $result = $this->getAllDatatables([],
        $this->getSelectedColumns(),
        [],'',[]);

        return $result;
    }

    // public function setTitleAttribute($slug)
    // {
    //     $slug = preg_replace("![^a-z0-9]+!i", "-", strtolower($slug));

    //     if(isset($this->id)){
    //         $obj = self::where('slug',$slug)->where('id','!=',$this->id)->first();
    //         $this->attributes['slug'] = $slug.'-'.((int)$this->id);
    //         $this->attributes['title'] = $title;
    //         return true;
    //     }
    //     $obj = self::where('slug',$slug)->first();
    //     if(isset($obj)){
    //         $this->attributes['slug'] = $slug.'-'.((int)$obj->id+1);
    //         return true;
    //     }
    //     $this->attributes['slug'] = $slug;
    //     return true;
    // }
    // public function user(){
    //     return $this->belongsTo(User::class,'user_id');
    // }
}
